name: PR Review Bot

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

jobs:
  pr-review:
    if: github.event_name == 'pull_request' || (github.event_name == 'issue_comment' && github.event.issue.pull_request)
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-dotenv PyGithub
        pip install llama-index llama-index-llms-openai
    
    - name: Get PR number
      id: pr_number
      run: |
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
        else
          echo "PR_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV
        fi
    
    - name: Run AI PR Review
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPOSITORY: ${{ github.repository }}
        PR_NUMBER: ${{ env.PR_NUMBER }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}
        OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
      run: |
        python agent.py
