name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: |
          poetry install --no-root
      - name: Run migrations
        run: |
          poetry run python manage.py migrate --noinput
      - name: Run pytest with coverage
        continue-on-error: true
        run: |
          poetry run coverage run -m pytest --junit-xml=pytest.xml || true
          poetry run coverage xml -o coverage.xml || true
      - name: Publish coverage results
        if: always()
        continue-on-error: true
        uses: aGallea/tests-coverage-report@v1
        with:
          cobertura-path: coverage.xml
          junit-path: pytest.xml
          show-diffcover: 'true'
      - name: Run agent
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: poetry run python agent.py